package com.lsb.init;

import com.gempire.init.ModItemProperties;

public class AddonItemProperties {
    public static void addCustomItemProperties() {

        //Moissanite
        ModItemProperties.makeGem(AddonItems.WHITE_SBMOISSANITE_GEM.get());
        ModItemProperties.makeGem(AddonItems.ORANGE_SBMOISSANITE_GEM.get());
        ModItemProperties.makeGem(AddonItems.MAGENTA_SBMOISSANITE_GEM.get());
        ModItemProperties.makeGem(AddonItems.LIGHT_BLUE_SBMOISSANITE_GEM.get());
        ModItemProperties.makeGem(AddonItems.YELLOW_SBMOISSANITE_GEM.get());
        ModItemProperties.makeGem(AddonItems.LIME_SBMOISSANITE_GEM.get());
        ModItemProperties.makeGem(AddonItems.PINK_SBMOISSANITE_GEM.get());
        ModItemProperties.makeGem(AddonItems.GRAY_SBMOISSANITE_GEM.get());
        ModItemProperties.makeGem(AddonItems.LIGHT_GRAY_SBMOISSANITE_GEM.get());
        ModItemProperties.makeGem(AddonItems.CYAN_SBMOISSANITE_GEM.get());
        ModItemProperties.makeGem(AddonItems.PURPLE_SBMOISSANITE_GEM.get());
        ModItemProperties.makeGem(AddonItems.BLUE_SBMOISSANITE_GEM.get());
        ModItemProperties.makeGem(AddonItems.BROWN_SBMOISSANITE_GEM.get());
        ModItemProperties.makeGem(AddonItems.GREEN_SBMOISSANITE_GEM.get());
        ModItemProperties.makeGem(AddonItems.RED_SBMOISSANITE_GEM.get());
        ModItemProperties.makeGem(AddonItems.BLACK_SBMOISSANITE_GEM.get());
        //Opal
        ModItemProperties.makeGem(AddonItems.WHITE_SBOPAL_GEM.get());
        ModItemProperties.makeGem(AddonItems.ORANGE_SBOPAL_GEM.get());
        ModItemProperties.makeGem(AddonItems.MAGENTA_SBOPAL_GEM.get());
        ModItemProperties.makeGem(AddonItems.LIGHT_BLUE_SBOPAL_GEM.get());
        ModItemProperties.makeGem(AddonItems.YELLOW_SBOPAL_GEM.get());
        ModItemProperties.makeGem(AddonItems.LIME_SBOPAL_GEM.get());
        ModItemProperties.makeGem(AddonItems.PINK_SBOPAL_GEM.get());
        ModItemProperties.makeGem(AddonItems.GRAY_SBOPAL_GEM.get());
        ModItemProperties.makeGem(AddonItems.LIGHT_GRAY_SBOPAL_GEM.get());
        ModItemProperties.makeGem(AddonItems.CYAN_SBOPAL_GEM.get());
        ModItemProperties.makeGem(AddonItems.PURPLE_SBOPAL_GEM.get());
        ModItemProperties.makeGem(AddonItems.BLUE_SBOPAL_GEM.get());
        ModItemProperties.makeGem(AddonItems.BROWN_SBOPAL_GEM.get());
        ModItemProperties.makeGem(AddonItems.GREEN_SBOPAL_GEM.get());
        ModItemProperties.makeGem(AddonItems.RED_SBOPAL_GEM.get());
        ModItemProperties.makeGem(AddonItems.BLACK_SBOPAL_GEM.get());
        //Jade
        ModItemProperties.makeGem(AddonItems.WHITE_SBJADE_GEM.get());
        ModItemProperties.makeGem(AddonItems.ORANGE_SBJADE_GEM.get());
        ModItemProperties.makeGem(AddonItems.MAGENTA_SBJADE_GEM.get());
        ModItemProperties.makeGem(AddonItems.LIGHT_BLUE_SBJADE_GEM.get());
        ModItemProperties.makeGem(AddonItems.YELLOW_SBJADE_GEM.get());
        ModItemProperties.makeGem(AddonItems.LIME_SBJADE_GEM.get());
        ModItemProperties.makeGem(AddonItems.PINK_SBJADE_GEM.get());
        ModItemProperties.makeGem(AddonItems.GRAY_SBJADE_GEM.get());
        ModItemProperties.makeGem(AddonItems.LIGHT_GRAY_SBJADE_GEM.get());
        ModItemProperties.makeGem(AddonItems.CYAN_SBJADE_GEM.get());
        ModItemProperties.makeGem(AddonItems.PURPLE_SBJADE_GEM.get());
        ModItemProperties.makeGem(AddonItems.BLUE_SBJADE_GEM.get());
        ModItemProperties.makeGem(AddonItems.BROWN_SBJADE_GEM.get());
        ModItemProperties.makeGem(AddonItems.GREEN_SBJADE_GEM.get());
        ModItemProperties.makeGem(AddonItems.RED_SBJADE_GEM.get());
        ModItemProperties.makeGem(AddonItems.BLACK_SBJADE_GEM.get());
        //Moonstone
        ModItemProperties.makeGem(AddonItems.WHITE_SBMOONSTONE_GEM.get());
        ModItemProperties.makeGem(AddonItems.ORANGE_SBMOONSTONE_GEM.get());
        ModItemProperties.makeGem(AddonItems.MAGENTA_SBMOONSTONE_GEM.get());
        ModItemProperties.makeGem(AddonItems.LIGHT_BLUE_SBMOONSTONE_GEM.get());
        ModItemProperties.makeGem(AddonItems.YELLOW_SBMOONSTONE_GEM.get());
        ModItemProperties.makeGem(AddonItems.LIME_SBMOONSTONE_GEM.get());
        ModItemProperties.makeGem(AddonItems.PINK_SBMOONSTONE_GEM.get());
        ModItemProperties.makeGem(AddonItems.GRAY_SBMOONSTONE_GEM.get());
        ModItemProperties.makeGem(AddonItems.LIGHT_GRAY_SBMOONSTONE_GEM.get());
        ModItemProperties.makeGem(AddonItems.CYAN_SBMOONSTONE_GEM.get());
        ModItemProperties.makeGem(AddonItems.PURPLE_SBMOONSTONE_GEM.get());
        ModItemProperties.makeGem(AddonItems.BLUE_SBMOONSTONE_GEM.get());
        ModItemProperties.makeGem(AddonItems.BROWN_SBMOONSTONE_GEM.get());
        ModItemProperties.makeGem(AddonItems.GREEN_SBMOONSTONE_GEM.get());
        ModItemProperties.makeGem(AddonItems.RED_SBMOONSTONE_GEM.get());
        ModItemProperties.makeGem(AddonItems.BLACK_SBMOONSTONE_GEM.get());
        //Gold
        ModItemProperties.makeGem(AddonItems.WHITE_SBGOLD_GEM.get());
        ModItemProperties.makeGem(AddonItems.YELLOW_SBGOLD_GEM.get());
        ModItemProperties.makeGem(AddonItems.PINK_SBGOLD_GEM.get());
        //Pyrite
        ModItemProperties.makeGem(AddonItems.SBPYRITE_GEM.get());
        //Platinum
        ModItemProperties.makeGem(AddonItems.SBPLATINUM_GEM.get());
        //Copper
        ModItemProperties.makeGem(AddonItems.COPPER_SBCOPPER_GEM.get());
        ModItemProperties.makeGem(AddonItems.OXIDIZED_SBCOPPER_GEM.get());
        ModItemProperties.makeGem(AddonItems.EXPOSED_SBCOPPER_GEM.get());
        ModItemProperties.makeGem(AddonItems.WEATHERED_SBCOPPER_GEM.get());
        //Silver
        ModItemProperties.makeGem(AddonItems.SBSILVER_GEM.get());
        //Jeremejevite
        ModItemProperties.makeGem(AddonItems.SBJEREMEJEVITE_GEM.get());
        //Zirconia
        ModItemProperties.makeGem(AddonItems.WHITE_SBZIRCONIA_GEM.get());
        ModItemProperties.makeGem(AddonItems.ORANGE_SBZIRCONIA_GEM.get());
        ModItemProperties.makeGem(AddonItems.MAGENTA_SBZIRCONIA_GEM.get());
        ModItemProperties.makeGem(AddonItems.LIGHT_BLUE_SBZIRCONIA_GEM.get());
        ModItemProperties.makeGem(AddonItems.YELLOW_SBZIRCONIA_GEM.get());
        ModItemProperties.makeGem(AddonItems.LIME_SBZIRCONIA_GEM.get());
        ModItemProperties.makeGem(AddonItems.PINK_SBZIRCONIA_GEM.get());
        ModItemProperties.makeGem(AddonItems.GRAY_SBZIRCONIA_GEM.get());
        ModItemProperties.makeGem(AddonItems.LIGHT_GRAY_SBZIRCONIA_GEM.get());
        ModItemProperties.makeGem(AddonItems.CYAN_SBZIRCONIA_GEM.get());
        ModItemProperties.makeGem(AddonItems.PURPLE_SBZIRCONIA_GEM.get());
        ModItemProperties.makeGem(AddonItems.BLUE_SBZIRCONIA_GEM.get());
        ModItemProperties.makeGem(AddonItems.BROWN_SBZIRCONIA_GEM.get());
        ModItemProperties.makeGem(AddonItems.GREEN_SBZIRCONIA_GEM.get());
        ModItemProperties.makeGem(AddonItems.RED_SBZIRCONIA_GEM.get());
        ModItemProperties.makeGem(AddonItems.BLACK_SBZIRCONIA_GEM.get());
    }
}
