package com.lsb.init;

import com.gempire.init.ModItemProperties;

public class AddonItemProperties {
    public static void addCustomItemProperties() {

        //Moissanite
        ModItemProperties.makeGem(AddonItems.WHITE_SBMOISSANITE_GEM.get());
        ModItemProperties.makeGem(AddonItems.ORANGE_SBMOISSANITE_GEM.get());
        ModItemProperties.makeGem(AddonItems.MAGENTA_SBMOISSANITE_GEM.get());
        ModItemProperties.makeGem(AddonItems.LIGHT_BLUE_SBMOISSANITE_GEM.get());
        ModItemProperties.makeGem(AddonItems.YELLOW_SBMOISSANITE_GEM.get());
        ModItemProperties.makeGem(AddonItems.LIME_SBMOISSANITE_GEM.get());
        ModItemProperties.makeGem(AddonItems.PINK_SBMOISSANITE_GEM.get());
        ModItemProperties.makeGem(AddonItems.GRAY_SBMOISSANITE_GEM.get());
        ModItemProperties.makeGem(AddonItems.LIGHT_GRAY_SBMOISSANITE_GEM.get());
        ModItemProperties.makeGem(AddonItems.CYAN_SBMOISSANITE_GEM.get());
        ModItemProperties.makeGem(AddonItems.PURPLE_SBMOISSANITE_GEM.get());
        ModItemProperties.makeGem(AddonItems.BLUE_SBMOISSANITE_GEM.get());
        ModItemProperties.makeGem(AddonItems.BROWN_SBMOISSANITE_GEM.get());
        ModItemProperties.makeGem(AddonItems.GREEN_SBMOISSANITE_GEM.get());
        ModItemProperties.makeGem(AddonItems.RED_SBMOISSANITE_GEM.get());
        ModItemProperties.makeGem(AddonItems.BLACK_SBMOISSANITE_GEM.get());
        //Opal
        ModItemProperties.makeGem(AddonItems.COOBER_PEDY_SBOPAL_GEM.get());
        ModItemProperties.makeGem(AddonItems.SLOVAKIAN_SBOPAL_GEM.get());
        ModItemProperties.makeGem(AddonItems.PERUVIAN_SBOPAL_GEM.get());
        ModItemProperties.makeGem(AddonItems.ETHIOPIAN_SBOPAL_GEM.get());
        ModItemProperties.makeGem(AddonItems.FIRE_SBOPAL_GEM.get());
        ModItemProperties.makeGem(AddonItems.TANZANIAN_SBOPAL_GEM.get());
        ModItemProperties.makeGem(AddonItems.ROSE_WATER_SBOPAL_GEM.get());
        ModItemProperties.makeGem(AddonItems.MINTABIE_SBOPAL_GEM.get());
        ModItemProperties.makeGem(AddonItems.CRYSTAL_SBOPAL_GEM.get());
        ModItemProperties.makeGem(AddonItems.CONTRALUZ_SBOPAL_GEM.get());
        ModItemProperties.makeGem(AddonItems.MORADO_SBOPAL_GEM.get());
        ModItemProperties.makeGem(AddonItems.HARLEQUIN_SBOPAL_GEM.get());
        ModItemProperties.makeGem(AddonItems.BOULDER_SBOPAL_GEM.get());
        ModItemProperties.makeGem(AddonItems.ANDAMOOKA_SBOPAL_GEM.get());
        ModItemProperties.makeGem(AddonItems.CHERRY_SBOPAL_GEM.get());
        ModItemProperties.makeGem(AddonItems.HONDURAN_SBOPAL_GEM.get());
        //Moonstone
        ModItemProperties.makeGem(AddonItems.WHITE_SBMOONSTONE_GEM.get());
        ModItemProperties.makeGem(AddonItems.ORANGE_SBMOONSTONE_GEM.get());
        ModItemProperties.makeGem(AddonItems.MAGENTA_SBMOONSTONE_GEM.get());
        ModItemProperties.makeGem(AddonItems.LIGHT_BLUE_SBMOONSTONE_GEM.get());
        ModItemProperties.makeGem(AddonItems.YELLOW_SBMOONSTONE_GEM.get());
        ModItemProperties.makeGem(AddonItems.LIME_SBMOONSTONE_GEM.get());
        ModItemProperties.makeGem(AddonItems.PINK_SBMOONSTONE_GEM.get());
        ModItemProperties.makeGem(AddonItems.GRAY_SBMOONSTONE_GEM.get());
        ModItemProperties.makeGem(AddonItems.LIGHT_GRAY_SBMOONSTONE_GEM.get());
        ModItemProperties.makeGem(AddonItems.CYAN_SBMOONSTONE_GEM.get());
        ModItemProperties.makeGem(AddonItems.PURPLE_SBMOONSTONE_GEM.get());
        ModItemProperties.makeGem(AddonItems.BLUE_SBMOONSTONE_GEM.get());
        ModItemProperties.makeGem(AddonItems.BROWN_SBMOONSTONE_GEM.get());
        ModItemProperties.makeGem(AddonItems.GREEN_SBMOONSTONE_GEM.get());
        ModItemProperties.makeGem(AddonItems.RED_SBMOONSTONE_GEM.get());
        ModItemProperties.makeGem(AddonItems.BLACK_SBMOONSTONE_GEM.get());
        //Gold
        ModItemProperties.makeGem(AddonItems.WHITE_SBGOLD_GEM.get());
        ModItemProperties.makeGem(AddonItems.YELLOW_SBGOLD_GEM.get());
        ModItemProperties.makeGem(AddonItems.PINK_SBGOLD_GEM.get());
        //Pyrite
        ModItemProperties.makeGem(AddonItems.SBPYRITE_GEM.get());
        //Platinum
        ModItemProperties.makeGem(AddonItems.SBPLATINUM_GEM.get());
        //Copper
        ModItemProperties.makeGem(AddonItems.COPPER_SBCOPPER_GEM.get());
        ModItemProperties.makeGem(AddonItems.OXIDIZED_SBCOPPER_GEM.get());
        ModItemProperties.makeGem(AddonItems.EXPOSED_SBCOPPER_GEM.get());
        ModItemProperties.makeGem(AddonItems.WEATHERED_SBCOPPER_GEM.get());
        //Silver
        ModItemProperties.makeGem(AddonItems.SBSILVER_GEM.get());
        //Jeremejevite
        ModItemProperties.makeGem(AddonItems.SBJEREMEJEVITE_GEM.get());
        //Zirconia
        ModItemProperties.makeGem(AddonItems.WHITE_SBZIRCONIA_GEM.get());
        ModItemProperties.makeGem(AddonItems.ORANGE_SBZIRCONIA_GEM.get());
        ModItemProperties.makeGem(AddonItems.MAGENTA_SBZIRCONIA_GEM.get());
        ModItemProperties.makeGem(AddonItems.LIGHT_BLUE_SBZIRCONIA_GEM.get());
        ModItemProperties.makeGem(AddonItems.YELLOW_SBZIRCONIA_GEM.get());
        ModItemProperties.makeGem(AddonItems.LIME_SBZIRCONIA_GEM.get());
        ModItemProperties.makeGem(AddonItems.PINK_SBZIRCONIA_GEM.get());
        ModItemProperties.makeGem(AddonItems.GRAY_SBZIRCONIA_GEM.get());
        ModItemProperties.makeGem(AddonItems.LIGHT_GRAY_SBZIRCONIA_GEM.get());
        ModItemProperties.makeGem(AddonItems.CYAN_SBZIRCONIA_GEM.get());
        ModItemProperties.makeGem(AddonItems.PURPLE_SBZIRCONIA_GEM.get());
        ModItemProperties.makeGem(AddonItems.BLUE_SBZIRCONIA_GEM.get());
        ModItemProperties.makeGem(AddonItems.BROWN_SBZIRCONIA_GEM.get());
        ModItemProperties.makeGem(AddonItems.GREEN_SBZIRCONIA_GEM.get());
        ModItemProperties.makeGem(AddonItems.RED_SBZIRCONIA_GEM.get());
        ModItemProperties.makeGem(AddonItems.BLACK_SBZIRCONIA_GEM.get());
        //Ammolite
        ModItemProperties.makeGem(AddonItems.SBAMMOLITE_GEM.get());
        //Calcite
        ModItemProperties.makeGem(AddonItems.WHITE_SBCALCITE_GEM.get());
        ModItemProperties.makeGem(AddonItems.ORANGE_SBCALCITE_GEM.get());
        ModItemProperties.makeGem(AddonItems.MAGENTA_SBCALCITE_GEM.get());
        ModItemProperties.makeGem(AddonItems.LIGHT_BLUE_SBCALCITE_GEM.get());
        ModItemProperties.makeGem(AddonItems.YELLOW_SBCALCITE_GEM.get());
        ModItemProperties.makeGem(AddonItems.LIME_SBCALCITE_GEM.get());
        ModItemProperties.makeGem(AddonItems.PINK_SBCALCITE_GEM.get());
        ModItemProperties.makeGem(AddonItems.GRAY_SBCALCITE_GEM.get());
        ModItemProperties.makeGem(AddonItems.LIGHT_GRAY_SBCALCITE_GEM.get());
        ModItemProperties.makeGem(AddonItems.CYAN_SBCALCITE_GEM.get());
        ModItemProperties.makeGem(AddonItems.PURPLE_SBCALCITE_GEM.get());
        ModItemProperties.makeGem(AddonItems.BLUE_SBCALCITE_GEM.get());
        ModItemProperties.makeGem(AddonItems.BROWN_SBCALCITE_GEM.get());
        ModItemProperties.makeGem(AddonItems.GREEN_SBCALCITE_GEM.get());
        ModItemProperties.makeGem(AddonItems.RED_SBCALCITE_GEM.get());
        ModItemProperties.makeGem(AddonItems.BLACK_SBCALCITE_GEM.get());
        ModItemProperties.makeGem(AddonItems.RAINBOW_SBCALCITE_GEM.get());
        //HOLTITE
        ModItemProperties.makeGem(AddonItems.SBHOLTITE_GEM.get());
        //CUPRITE
        ModItemProperties.makeGem(AddonItems.SBCUPRITE_GEM.get());
    }
}
